version: "3"

services:
  traefik:
    image: "traefik:v2.0.2"
    container_name: "${PROJECT_NAME}_traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      # Enabling docker provider
      - "--providers.docker=true"
      # Do not expose containers unless explicitly told so
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.rule=Host(`monitor.localhost`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  portainer:
    image: portainer/portainer
    container_name: "${PROJECT_NAME}_portainer-s"
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_portainer.rule=Host(`portainer.${PROJECT_BASE_URL}`)"

  apache:
      build: ./docker/apache
      container_name: "${PROJECT_NAME}_portainer"
      depends_on:
          - mysql
      volumes:
          - ./docker/apache/apache2.conf:/etc/apache2/conf-enabled/apache2.conf:ro
          - ./docker/apache/php.ini:/usr/local/etc/php/php.ini
          - ./:/var/www/html:cached
      expose:
          - 80
      labels:
          - "traefik.enable=true"
          - "traefik.http.routers.apache.rule=Host(`localhost`)"
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}_pma"
    environment:
      PMA_HOST: $DATABASE_HOST
      PMA_USER: $DATABASE_USER
      PMA_PASSWORD: $DATABASE_PASSWORD
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_pma.rule=Host(`pma.${PROJECT_BASE_URL}`)"

  mysql:
    image: mysql:${MYSQL_TAG}
    container_name: "${PROJECT_NAME}_mysql"
    environment:
      MYSQL_ROOT_PASSWORD: $DATABASE_ROOT_PASSWORD
      MYSQL_DATABASE: $DATABASE_NAME
      MYSQL_USER: $DATABASE_USER
      MYSQL_PASSWORD: $DATABASE_PASSWORD
    volumes:
        - ./docker/mysql/data:/var/lib/mysql
